### ISSUE TITLE
Enhancement and Issue Notes.

### ISSUE THREAD

**Issue by Zaymes** [okfnepal/idms-page#1]
### Acceptance Criteria

- [x] I have identified different styles, enhancement issues added them in the issues list
- [x] I have resolved and opened  issues for required enhancements

### Issues lists

- [x] Reading Section Contains dummy data. Configure it to fetch IDMS-tagged blogs from oknp website.
- [x] Smooth button for showcase in homepage
- [x] Explore and finalize the hero and IDMS for section images

**Comment by sagargg** [comment]
@Zaymes  Here are some review feedbacks. 

1. Logo not align 
<img width="1512" alt="Screenshot 2024-02-05 at 9 05 13 AM" src="https://github.com/okfnepal/idms-page/assets/87696933/56c9fa70-77b2-4c17-8af8-7d69e18a4304">
2.  Remove some padding 
<img width="1512" alt="Screenshot 2024-02-05 at 9 08 15 AM" src="https://github.com/okfnepal/idms-page/assets/87696933/7783fb78-7eae-40c4-8487-06d2b5ffeb70">

3.  Learn more link not clickable. 
<img width="1489" alt="Screenshot 2024-02-05 at 9 09 07 AM" src="https://github.com/okfnepal/idms-page/assets/87696933/fc413462-b71c-415f-b9e6-fb2c2356f241">

4. Good to have a hover effect, eg. the Background would be light green if user hover the containe
<img width="1394" alt="Screenshot 2024-02-05 at 9 06 55 AM" src="https://github.com/okfnepal/idms-page/assets/87696933/6ba1c084-d89b-4364-aa26-d492d9f655c9">

5. inconsistent hights on icons 
<img width="1458" alt="Screenshot 2024-02-05 at 9 10 48 AM" src="https://github.com/okfnepal/idms-page/assets/87696933/a2d1c389-ec37-4c98-9bd0-fdbc86ffd0a7">

6. These images do not look good, try with a simple clipart. 
<img width="1509" alt="Screenshot 2024-02-05 at 9 12 21 AM" src="https://github.com/okfnepal/idms-page/assets/87696933/71fdfffb-998e-4809-a235-c5b4aa63f5d9">

7. Make the whole container clickable and maybe add a hover effect as well with a background change. 
<img width="1488" alt="Screenshot 2024-02-05 at 9 14 17 AM" src="https://github.com/okfnepal/idms-page/assets/87696933/74e2e4ab-bca6-4b5b-a3c9-957e0c64396f">

8. Dropdown as a container view, maybe with a border or shadows. 
<img width="265" alt="Screenshot 2024-02-05 at 9 16 03 AM" src="https://github.com/okfnepal/idms-page/assets/87696933/11f503b6-7460-4e91-a96a-72f237637d0e">

9. Increase header container as main page. 
<img width="1512" alt="Screenshot 2024-02-05 at 9 17 43 AM" src="https://github.com/okfnepal/idms-page/assets/87696933/753068ee-d8e8-43c9-b295-28bfd67b3511">

**Comment by sagargg** [comment]
@Zaymes  One last minor feedback, could you try another image here, and color one that matches with main color. 
<img width="1338" alt="Screenshot 2024-02-08 at 8 22 23 PM" src="https://github.com/okfnepal/idms-page/assets/87696933/16d29a06-86e8-4878-8f16-7654d16429b7">

**Comment by Zaymes** [comment]
@sagargg dai can we go with this
![image](https://github.com/okfnepal/idms-page/assets/28755348/47ac0a6e-c0d8-458e-8ab5-1f41583b7e7b)

**Comment by Zaymes** [comment]
Fixed all the major enhancements listed and closing this as done!
