### ISSUE TITLE
Add powered by CKAN logo

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/idms-page#2]
Currently the IDMS page doesn't have the acknowledgment to the CKAN. We need to add it so that we properly acknowledge the contribution of open-source technologies.

### Tasks
- [x] Find the space on the page, to write and include the powered by CKAN logo

**Comment by Zaymes** [comment]
@nikeshbalami can we go with this
![image](https://github.com/okfnepal/idms-page/assets/28755348/4f290f6f-2282-4673-8f41-44076423f03b)

**Comment by nikeshbalami** [comment]
Let's reduce the size of the CKAN logo. Otherwise, we are good to go.

**Comment by Zaymes** [comment]
Closing as DONE!
