### ISSUE TITLE
Logo alignment and showcase link not working

### ISSUE THREAD

**Issue by sagargg** [okfnepal/idms-page#4]
**Logo** (Issue on safari browser )
<img width="1512" alt="Screenshot 2024-02-20 at 8 29 28 AM" src="https://github.com/okfnepal/idms-page/assets/87696933/3c52bcde-e2e8-41b4-9187-0671f9a263a6">

**Link**
<img width="1512" alt="Screenshot 2024-02-20 at 8 30 13 AM" src="https://github.com/okfnepal/idms-page/assets/87696933/7fd92320-e7da-41f6-91c9-5ab29068ebd0">

## Tasks
* [x] Fix identified issues and deploy.

**Comment by Zaymes** [comment]
Closing as done
